[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
slug = "{project_slug}"
entrypoint = "hello.py"

[branding]
name = "Job Dataset Project"
logo = "images/images.png"
favicon = "images/new_fav.ico"
primaryColor = "#F89613"

[data.sample_csv]
type = "csv"
path = "data/ai_job_dataset.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 
